# Generated by Django 4.0.2 on 2022-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Place', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
            ],
        ),
    ]
