# Generated by Django 4.0.2 on 2022-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0002_alter_owner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Place', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='owner',
        ),
    ]
