# Generated by Django 4.0.2 on 2022-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0003_file_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Place', models.CharField(max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('remarks', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
