# Generated by Django 4.0.3 on 2022-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0005_profile_turfimages_alter_owner_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turf_images/'),
        ),
    ]
