# Generated by Django 4.0.3 on 2022-03-02 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfapp', '0006_alter_turfimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
