# Generated by Django 4.0.3 on 2022-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0008_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='order_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
