# Generated by Django 4.0.3 on 2022-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0009_bookings_order_id_bookings_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('contact', models.CharField(default='', max_length=10)),
                ('ownername', models.CharField(default='', max_length=100)),
                ('turfdetails', models.CharField(default='', max_length=100, unique=True)),
                ('complaint', models.TextField()),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]
