# Generated by Django 4.0.3 on 2022-03-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0011_alter_post_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
